version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # https://github.com/dependabot/dependabot-core/issues/6345
      - "/.github/actions/*"
      - "/.github/actions/setup/*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
      exclude:
        - "itoutils"
    commit-message:
      prefix: "requirement"
      prefix-development: "dev requirement"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 20
    allow:
      - dependency-type: all
