services:
  # https://github.com/appropriate/docker-postgis
  # https://hub.docker.com/r/mdillon/postgis/tags
  postgres:
    container_name: api_relay_cnav_postgres
    image: postgres:18
    # Disable some safety switches for a faster postgres: https://www.postgresql.org/docs/current/non-durability.html
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      # Required by the "_/postgres" image
      # https://registry.hub.docker.com/_/postgres/
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=${PGDATABASE:-api_relay_cnav}
      # Avoid a log error when starting the api_relay_cnav_postgres:
      # > Role "root" does not exist.
      # Without this variable, the default Unix account ('root')
      # is used automatically when starting postgres.
      # https://www.postgresql.org/docs/current/libpq-envars.html
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql
      - type: bind
        source: ${PWD}/docker/dev/postgres
        target: /var/run/postgresql/
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT_ON_DOCKER_HOST:-5432}:5432"

  django:
    profiles: ["django"]
    container_name: api_relay_cnav_django
    environment:
      - DJANGO_DB_HOST=postgres
      - DJANGO_ENVIRONMENT=DEV
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: dev_image
    restart: unless-stopped
    volumes:
      - ./api_relay_cnav:/app/api_relay_cnav
      - ./tests:/app/tests
      - ./README.md:/app/README.md
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    ports:
      - "127.0.0.1:${DJANGO_PORT_ON_DOCKER_HOST:-8000}:8000"
    # Make interactive debugging possible.
    # Source: https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
    # Run the usual `make run` (`docker-compose up`) and then in a second terminal run `docker attach api_relay_cnav_django`.
    # You should now be able to access the usual interactive debugger on that second terminal.
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  postgres_data:
