"""
Django settings for api_relay_cnav project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import enum
import os
from pathlib import Path

import environ


class Environment(enum.StrEnum):
    BUILD = "BUILD"
    PROD = "PROD"
    TEST = "TEST"
    DEV = "DEV"


env = environ.FileAwareEnv()

env.prefix = "DJANGO_"
ENVIRONMENT = Environment(env.str("ENVIRONMENT", choices=Environment))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env.str("SECRET_KEY") if ENVIRONMENT is Environment.PROD else "foobar"

_default_allow_list = []
if ENVIRONMENT is Environment.DEV:
    _default_allow_list = ["localhost", "127.0.0.1", "192.168.0.1", "0.0.0.0"]
    if runserver_domain := os.getenv("RUNSERVER_DOMAIN"):
        _default_allow_list.append(runserver_domain.split(":")[0])

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=_default_allow_list)

DEBUG = env.bool("DEBUG", default=True) if ENVIRONMENT is Environment.DEV else False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
if ENVIRONMENT is Environment.DEV:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    # Generate request Id
    "django_datadog_logger.middleware.request_id.RequestIdMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Final logger
    "django_datadog_logger.middleware.request_log.RequestLoggingMiddleware",
]
if ENVIRONMENT is Environment.DEV:
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")


ROOT_URLCONF = "api_relay_cnav.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "api_relay_cnav.wsgi.application"


db_statement_timeout = env.int("WWW_DB_STATEMENT_TIMEOUT", default=10_000)
db_lock_timeout = env.int("WWW_DB_LOCK_TIMEOUT", default=5_000)

DATABASES = {
    "default": {
        "ATOMIC_REQUESTS": True,
        # Since we have the health checks enabled, no need to define a max age:
        # if the connection was closed on the database side, the check will detect it
        "CONN_MAX_AGE": None,
        "CONN_HEALTH_CHECKS": True,
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DB_NAME", "api_relay_cnav"),
        "HOST": env.str("DB_HOST", "127.0.0.1"),
        "PORT": env.int("DB_PORT", 5432),
        "USER": env.str("DB_USER", "postgres"),
        "PASSWORD": env.str("DB_PASSWORD", "password"),
        "OPTIONS": {
            "connect_timeout": 5,
            "options": f"-c statement_timeout={db_statement_timeout} -c lock_timeout={db_lock_timeout}",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 16},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "fr-FR"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static_collected"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {"()": "django_datadog_logger.formatters.datadog.DatadogJSONFormatter"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "json"},
        "null": {"class": "logging.NullHandler"},
    },
    "loggers": {
        "": {"handlers": ["console"], "level": "INFO"},
    },
}
