"""
Django settings for api_relay_cnav project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import enum
import os
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP

from api_relay_cnav.utils.token import token_hexdigest


class Environment(enum.StrEnum):
    BUILD = "BUILD"
    PROD = "PROD"
    TEST = "TEST"
    DEV = "DEV"


class Service(enum.StrEnum):
    ALL = "ALL"
    BACKOFFICE = "BACKOFFICE"
    API = "API"


env = environ.FileAwareEnv()

env.prefix = "DJANGO_"
ENVIRONMENT = Environment(env.str("ENVIRONMENT", choices=Environment))
SERVICE = Service(env.str("SERVICE", choices=Service, default=Service.ALL))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env.str("SECRET_KEY") if ENVIRONMENT is Environment.PROD else "foobar"
# Previous key, kept verifiable during one SECRET_KEY rotation cycle
SECRET_KEY_FALLBACKS = [key for key in env.list("SECRET_KEY_FALLBACKS", default=[]) if key]

_default_allow_list = []
if ENVIRONMENT is Environment.DEV:
    _default_allow_list = ["localhost", "127.0.0.1", "192.168.0.1", "0.0.0.0"]
    if runserver_domain := os.getenv("RUNSERVER_DOMAIN"):
        _default_allow_list.append(runserver_domain.split(":")[0])

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=_default_allow_list)

DEBUG = env.bool("DEBUG", default=True) if ENVIRONMENT is Environment.DEV else False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "drf_standardized_errors",
    # Project apps
    "api_relay_cnav.users",
    "api_relay_cnav.utils",
]
if ENVIRONMENT is Environment.DEV:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    # Generate request Id
    "django_datadog_logger.middleware.request_id.RequestIdMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # No-op unless this pod uses Authentik forwardAuth (gated by AUTHENTIK_FORWARD_AUTH).
    "api_relay_cnav.users.middleware.AuthentikRemoteUserMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    # Final logger
    "django_datadog_logger.middleware.request_log.RequestLoggingMiddleware",
]
if ENVIRONMENT is Environment.DEV:
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")


# Per-service URL routing.
# SERVICE=ALL (the DEV/TEST default) serves every service from one process via the combined urlconf
# Each production pod serves a single service
match SERVICE, ENVIRONMENT:
    case Service.ALL, Environment.PROD:
        raise ImproperlyConfigured("A production pod must set DJANGO_SERVICE to BACKOFFICE or API.")
    case Service.ALL, _:
        ROOT_URLCONF = "api_relay_cnav.urls"
    case Service.BACKOFFICE, _:
        ROOT_URLCONF = "api_relay_cnav.urls_backoffice"
    case Service.API, _:
        raise ImproperlyConfigured("The API service is not implemented yet.")


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "api_relay_cnav.wsgi.application"


db_statement_timeout = env.int("WWW_DB_STATEMENT_TIMEOUT", default=10_000)
db_lock_timeout = env.int("WWW_DB_LOCK_TIMEOUT", default=5_000)

DATABASES = {
    "default": {
        "ATOMIC_REQUESTS": True,
        # Since we have the health checks enabled, no need to define a max age:
        # if the connection was closed on the database side, the check will detect it
        "CONN_MAX_AGE": None,
        "CONN_HEALTH_CHECKS": True,
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DB_NAME", "api_relay_cnav"),
        "HOST": env.str("DB_HOST", "127.0.0.1"),
        "PORT": env.int("DB_PORT", 5432),
        "USER": env.str("DB_USER", "postgres"),
        "PASSWORD": env.str("DB_PASSWORD", "password"),
        "OPTIONS": {
            "connect_timeout": 5,
            "options": f"-c statement_timeout={db_statement_timeout} -c lock_timeout={db_lock_timeout}",
        },
    }
}

# Application role receiving DML grants after each migrations run (see the grant_app_privileges command)
DB_APP_ROLE = env.str("DB_APP_ROLE", default="")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 16},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Custom user model
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/#auth-custom-user

AUTH_USER_MODEL = "users.User"


SECURE_CSP = {
    "default-src": [CSP.NONE],
    "img-src": [CSP.SELF],
    "script-src-elem": [CSP.SELF],
    "style-src": [CSP.SELF],
}


LANGUAGE_CODE = "fr-FR"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static_collected"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {"()": "django_datadog_logger.formatters.datadog.DatadogJSONFormatter"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "json"},
        "null": {"class": "logging.NullHandler"},
    },
    "loggers": {
        "": {"handlers": ["console"], "level": "INFO"},
    },
}


REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_standardized_errors.openapi.AutoSchema",
    # Drop permissive defaults and force views to define both
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "API - Relai vers la CNAV",
    "DESCRIPTION": "Documentation de l'API",
    "VERSION": "1.0.0",
    "ENUM_NAME_OVERRIDES": {
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
    "POSTPROCESSING_HOOKS": ["drf_standardized_errors.openapi_hooks.postprocess_schema_enums"],
}

HASHED_API_TOKEN = env.str("HASHED_API_TOKEN") if ENVIRONMENT is Environment.PROD else token_hexdigest("Secret-Token")


# Authentik forwardAuth (backoffice auth)
# AuthentikRemoteUserMiddleware is always present in MIDDLEWARE but is a no-op unless this flag is set
AUTHENTIK_FORWARD_AUTH = ENVIRONMENT is Environment.PROD and SERVICE is Service.BACKOFFICE
AUTHENTIK_CREATE_UNKNOWN_USER = env.bool("AUTHENTIK_CREATE_UNKNOWN_USER", default=True)

if AUTHENTIK_FORWARD_AUTH:
    # No password login authorized in prod: Authentik (RemoteUser) is the only backend
    AUTHENTICATION_BACKENDS = ["api_relay_cnav.users.backends.AuthentikRemoteUserBackend"]

    # Redirect the admin logout to Authentik's sign-out (a local logout alone is useless behind forwardAuth)
    LOGOUT_REDIRECT_URL = env.str("AUTHENTIK_LOGOUT_URL")

# Security improvements behind the reverse proxy in PROD (Traefik)
if ENVIRONMENT is Environment.PROD:
    # Trust the proxy's X-Forwarded-Proto
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

    # Traefik already redirects HTTP to HTTPS
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    # Keep plain-HTTP probes working if the redirect is enabled
    SECURE_REDIRECT_EXEMPT = [r"^healthcheck/"]

    # Force secure cookies storage
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Make HSTS configurable (still disabled by default)
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

    # Origins allowed for CSRF (admin forms on the backoffice domain)
    CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
