# Generated by Django 6.0.7 on 2026-07-24 10:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterOpsCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(verbose_name="horodatage", auto_now_add=True)),
                (
                    "request_uid",
                    models.UUIDField(
                        verbose_name="Identifiant de la requête", help_text="Fourni par le client", db_index=True
                    ),
                ),
                ("request_content", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("interops_request_content", models.TextField()),
                ("interops_response_content", models.TextField()),
                (
                    "interops_response_status_code",
                    models.PositiveSmallIntegerField(verbose_name="Code de statut HTTP de la réponse InterOps"),
                ),
                (
                    "response_content",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
                ),
            ],
            options={
                "verbose_name": "appel à InterOps",
                "verbose_name_plural": "appels à InterOps",
            },
        ),
    ]
