# Generated by Django 6.0.6 on 2026-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RateLimitCounter",
                    fields=[
                        (
                            "pk",
                            models.CompositePrimaryKey(
                                "limiter_key",
                                "client_key",
                                "bucket_key",
                                blank=True,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("limiter_key", models.TextField(verbose_name="Identifiant du limiteur")),
                        ("client_key", models.TextField(verbose_name="Clef concernée par la limitation")),
                        ("bucket_key", models.BigIntegerField(verbose_name="Identifiant du bucket")),
                        ("bucket_count", models.PositiveIntegerField(verbose_name="Compteur du bucket")),
                        (
                            "cleanup_timestamp",
                            models.DateTimeField(verbose_name="Date à partir de laquelle la ligne peut être nettoyée"),
                        ),
                    ],
                ),
            ],
            # An UNLOGGED table is enough for rate limiting
            database_operations=[
                migrations.RunSQL(
                    'CREATE UNLOGGED TABLE "rate_limit_ratelimitcounter" ("limiter_key" text NOT NULL, "client_key" text NOT NULL, "bucket_key" bigint NOT NULL, "bucket_count" integer NOT NULL CHECK ("bucket_count" >= 0), "cleanup_timestamp" timestamp with time zone NOT NULL, PRIMARY KEY ("limiter_key", "client_key", "bucket_key"));'
                )
            ],
        )
    ]
