[uwsgi]
# Application loading
chdir = /app
home = /app/.venv
module = api_relay_cnav.wsgi:application
master = true
need-app = true

processes = 5
http = 0.0.0.0:8000
vacuum = true
die-on-term = true

# Safety options
harakiri = 30
max-requests = 5000

# Let uWSGI handle static files
static-map = /static=/app/static_collected
offload-threads = 4
