from django.core.management import call_command
from django.db import connection


def role_has_table_privileges(role, table, privileges):
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT bool_and(has_table_privilege(%s, %s, privilege)) FROM unnest(%s::text[]) AS privilege",
            [role, table, privileges],
        )
        return cursor.fetchone()[0]


class TestGrantAppPrivileges:
    DML = ["SELECT", "INSERT", "UPDATE", "DELETE"]
    DDL = ["TRUNCATE", "TRIGGER"]

    def test_skipped_when_no_role_is_configured(self, settings, caplog):
        settings.DB_APP_ROLE = ""
        call_command("grant_app_privileges")
        assert "DB_APP_ROLE is not set, skipping." in caplog.messages

    def test_grants_dml_on_existing_and_future_objects(self, settings):
        settings.DB_APP_ROLE = "test_app_role"

        with connection.cursor() as cursor:
            cursor.execute("CREATE ROLE test_app_role")

        call_command("grant_app_privileges")

        assert role_has_table_privileges("test_app_role", "users_user", self.DML) is True
        for privilege in self.DDL:
            assert role_has_table_privileges("test_app_role", "users_user", [privilege]) is False

        with connection.cursor() as cursor:
            cursor.execute("SELECT has_schema_privilege('test_app_role', 'public', 'CREATE')")
            assert cursor.fetchone()[0] is False

        # Table created after the command ran, as one from a future migration
        with connection.cursor() as cursor:
            cursor.execute("CREATE TABLE utils_smoke (id bigint GENERATED BY DEFAULT AS IDENTITY)")
        assert role_has_table_privileges("test_app_role", "utils_smoke", self.DML) is True

        with connection.cursor() as cursor:
            cursor.execute("SELECT has_sequence_privilege('test_app_role', 'utils_smoke_id_seq', 'USAGE')")
            assert cursor.fetchone()[0] is True
